# Generated by Django 4.2.7 on 2023-12-01 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Door',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='frontend/static/img')),
                ('isOpen', models.BooleanField(default=False)),
            ],
        ),
    ]
